#!/usr/bin/env python3
"""
SessionStart hook — keeps project-scoped feature-forge memory up to date.

On every session start, regenerates `<project>/.claude/CLAUDE.md` with an
auto-built inventory of the skills and agents bundled in this plugin, so
Claude Code always sees the available tools and doesn't forget them as the
conversation grows.

Design:
- `<project>/.claude/CLAUDE.md` is fully owned by feature-forge and rewritten
  every session. Users who want their own project instructions put them in
  `<project>/CLAUDE.md` at the repo root, which this hook never touches.
- Write only when content actually changes (hash compare) — SessionStart
  runs on every session, and noisy writes churn mtimes and git diffs.
- Resolve the plugin root from __file__, not CLAUDE_PLUGIN_ROOT: Claude Code
  bug #27145 can leave that variable unset for SessionStart events.

Contract: always print JSON with continue=true so startup is never blocked.
"""

import hashlib
import json
import os
import re
import sys


PLUGIN_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
SKILLS_DIR = os.path.join(PLUGIN_ROOT, "skills")
AGENTS_DIR = os.path.join(PLUGIN_ROOT, "agents")


def project_cwd() -> str:
    """Session working directory (CLAUDE_PROJECT_DIR, fallback to cwd)."""
    return os.environ.get("CLAUDE_PROJECT_DIR") or os.getcwd()


def emit(payload: dict) -> None:
    sys.stdout.write(json.dumps(payload))
    sys.stdout.flush()
    sys.exit(0)


def parse_frontmatter(path: str) -> dict:
    """Extract YAML-ish frontmatter from a markdown file. Returns {} on miss."""
    try:
        with open(path, "r", encoding="utf-8") as f:
            text = f.read()
    except OSError:
        return {}

    if not text.startswith("---"):
        return {}

    end = text.find("\n---", 3)
    if end == -1:
        return {}

    body = text[3:end].strip()
    out: dict = {}
    current_key = None
    buf: list = []

    def flush():
        if current_key is not None:
            out[current_key] = " ".join(buf).strip()

    for line in body.splitlines():
        m = re.match(r"^([A-Za-z_-]+):\s*(.*)$", line)
        if m:
            flush()
            current_key = m.group(1)
            buf = [m.group(2)]
        elif line.strip().startswith(("  ", "\t")) or (line and line[0] == " "):
            buf.append(line.strip())
        else:
            flush()
            current_key = None
            buf = []
    flush()
    return out


def first_role_paragraph(path: str) -> str:
    """Pull the first paragraph under '## Role' as a short agent description."""
    try:
        with open(path, "r", encoding="utf-8") as f:
            text = f.read()
    except OSError:
        return ""

    m = re.search(r"(?ms)^##\s+Role\s*\n\s*\n(.+?)(?:\n\s*\n|\Z)", text)
    if not m:
        return ""

    para = " ".join(line.strip() for line in m.group(1).strip().splitlines())
    return re.sub(r"\s+", " ", para)


def collect_skills() -> list:
    if not os.path.isdir(SKILLS_DIR):
        return []
    skills = []
    for entry in sorted(os.listdir(SKILLS_DIR)):
        skill_md = os.path.join(SKILLS_DIR, entry, "SKILL.md")
        if not os.path.isfile(skill_md):
            continue
        meta = parse_frontmatter(skill_md)
        name = meta.get("name") or entry
        desc = meta.get("description") or ""
        skills.append((name, desc))
    return skills


def collect_agents() -> list:
    if not os.path.isdir(AGENTS_DIR):
        return []
    agents = []
    for entry in sorted(os.listdir(AGENTS_DIR)):
        if not entry.endswith(".md"):
            continue
        path = os.path.join(AGENTS_DIR, entry)
        name = entry[:-3]
        desc = first_role_paragraph(path)
        agents.append((name, desc))
    return agents


def render_claude_md(skills: list, agents: list) -> str:
    lines = [
        "<!-- AUTOGENERATED BY feature-forge session-init hook — do not edit by hand. -->",
        "<!-- Your own project instructions belong in <project>/CLAUDE.md at the repo root. -->",
        "",
        "# feature-forge — available tools",
        "",
        "This project has the `feature-forge` Claude Code plugin installed.",
        "The skills and agents listed below are available for you (the assistant)",
        "to invoke. Prefer them over improvising when the task matches.",
        "",
        "## Skills",
        "",
        "Invoke with the `Skill` tool. Each skill is a self-contained workflow.",
        "",
    ]
    if not skills:
        lines.append("_(No skills detected.)_")
    else:
        for name, desc in skills:
            lines.append(f"- **`{name}`** — {desc}" if desc else f"- **`{name}`**")
    lines += [
        "",
        "## Agents",
        "",
        "Dispatch with the `Agent` tool (`subagent_type` = the name below).",
        "Agents run in isolated context — use them for parallel or read-only work.",
        "",
    ]
    if not agents:
        lines.append("_(No agents detected.)_")
    else:
        for name, desc in agents:
            lines.append(f"- **`{name}`** — {desc}" if desc else f"- **`{name}`**")
    lines += [
        "",
        "## Hooks (active)",
        "",
        "- `prompt-router` — classifies each user message and steers toward the right skill.",
        "- `workflow-gate` — enforces approval gate between decompose and implement phases.",
        "- `subagent-write-guard` — prevents sub-agents from writing outside their sandbox.",
        "- `session-init` — regenerates this file on each session start.",
        "",
        "Type `#bypass` in your next message if the router misclassifies.",
        "",
    ]
    return "\n".join(lines) + "\n"


def write_if_changed(path: str, content: str) -> bool:
    """Write content only if the file's current hash differs. Returns True on write."""
    new_hash = hashlib.sha256(content.encode("utf-8")).hexdigest()
    if os.path.isfile(path):
        try:
            with open(path, "rb") as f:
                existing_hash = hashlib.sha256(f.read()).hexdigest()
            if existing_hash == new_hash:
                return False
        except OSError:
            pass

    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    return True


def main() -> None:
    ok = {"continue": True, "suppressOutput": True, "status": "ready"}

    try:
        cwd = project_cwd()
        target = os.path.join(cwd, ".claude", "CLAUDE.md")
        skills = collect_skills()
        agents = collect_agents()
        content = render_claude_md(skills, agents)
        wrote = write_if_changed(target, content)
    except Exception:
        # Never block a session on setup failure.
        emit(ok)
        return

    if not wrote:
        emit(ok)
        return

    emit({
        "continue": True,
        "suppressOutput": False,
        "status": "ready",
        "systemMessage": (
            f"feature-forge: refreshed .claude/CLAUDE.md with "
            f"{len(skills)} skills and {len(agents)} agents."
        ),
    })


if __name__ == "__main__":
    main()
